src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

src/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_task/', views.add_task, name='add_task'),
    path('edit_task/<int:task_id>', views.edit_task, name='edit_task'),
    path('delete_task/<int:task_id>', views.delete_task, name='delete_task'),
    path('mark_completed/<int:task_id>', views.mark_completed, name='mark_completed'),
]

src/todo/models.py
from django.db import models
from datetime import date
from django.core.exceptions import ValidationError

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)

    class Meta:
        ordering = ['deadline']

    def clean(self):
        """ custom validation to ensure deadline is in future"""
        if self.deadline <= date.today():
            raise ValidationError("The deadline must be in the future.")
    
    def save(self, *args, **kwargs):
        """ Ensure clean is called before saving the object"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

src/todo/forms.py
from django import forms
from .models import Task


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline']
        widgets = {
        'title': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter task title',
        }),
        'description': forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Enter task description (optional)',
            'rows': 3,
        }),
        'deadline': forms.DateInput(attrs={
            'class': 'form-control',
            'type': 'date',
        }),
}

src/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import AddTaskForm
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    all_tasks = Task.objects.all()
    paginator = Paginator(all_tasks, 5)
    page_number = request.GET.get("page")
    task_list = paginator.get_page(page_number)
    
    task_count = Task.objects.count()
    context = {'task_list': task_list, 'task_count': task_count}
    return render(request, 'todo/index.html', context=context)

def add_task(request):
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:index')
        # Don't overwrite the form if it's invalid
        return render(request, 'todo/add_task.html', {'form': form})

    # Render an empty form for GET requests
    form = AddTaskForm()
    return render(request, 'todo/add_task.html', {'form': form})

def edit_task(request, task_id):
    task = Task.objects.get(pk = task_id)
    form = AddTaskForm(instance= task)
    if request.method == "POST":
        form = AddTaskForm(request.POST, instance= form)
        if form.is_valid():
            form.save()
            return redirect('todo:index')
    return render(request, 'todo/edit_task.html', {'form' : form})

def delete_task(request, task_id):
    task = Task.objects.get(pk = task_id)
    task.delete()
    return redirect('todo:index')

def mark_completed(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == "POST":
        is_completed = request.POST.get("is_completed") == "true"
        task.is_completed = is_completed
        task.save()
    return redirect("todo:index")


        

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}Todo App{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          Todo App
        </a>
      </div>
    </nav>

    <div class="container-sm" style="margin-top: 70px;">
      <div class="custom-container p-3 m-3 mx-auto border">
        {% block content %}

        {% endblock %}
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

src/todo/templates/todo/add_task.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h5 class="mb-0"><strong>Add New Task</strong></h5>
    </div>

    <form action="{% url 'todo:index' %}" method="get" style="display: inline;">
        <button type="submit" class="btn btn-danger">Back to Main Page</button>
    </form>
</div>

    <form action="/add_task/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.title.errors %}
        <div class="text-danger">
            {% for error in form.title.errors %}
                {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        <input type="submit" class="btn btn-success" value="Submit">
    </form>
    
{% endblock  %}

src/todo/templates/todo/edit_task.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h5 class="mb-0"><strong>Edit Task</strong></h5>
    </div>

    <form action="{% url 'todo:index' %}" method="get" style="display: inline;">
        <button type="submit" class="btn btn-danger">Back to Main Page</button>
    </form>
</div>




<form action="/add_task/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Submit">
</form>

    
{% endblock  %}

src/todo/templates/todo/index.html
{% extends "base.html" %}

{% block title %}Todo App{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h5 class="mb-0"><strong>Task List</strong></h5>
        <p class="text-muted mb-0">You have {{ task_count }} tasks left!</p>
    </div>
    <form action="{% url 'todo:add_task' %}" method="get" style="display: inline;">
        <button type="submit" class="btn btn-success">Add Task</button>
    </form>
</div>

<ul class="list-group">
    {% for task in task_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex">

            <form action="{% url 'todo:mark_completed' task.pk %}" method="post">
                {% csrf_token %}
                <input type="checkbox" 
                       class="form-check-input me-3" 
                       style="width: 1.5rem; height: 1.5rem;" 
                       name="is_completed" 
                       value="true"
                       {% if task.is_completed %}checked disabled{% endif %}
                       onchange="this.form.submit();">
            </form>
        


            <!-- Task Details -->
            <div>
                <strong>{{ task.title }}</strong>

                {% if task.description %}
                <p class="mb-1 text-muted">{{ task.description }}</p>
                {% endif %}
            </div>
        </div>

        <!-- Buttons -->
        <div>
            <form action="{% url "todo:edit_task" task.pk %}" method="get" style="display: inline;">
            <button class="btn btn-sm btn-dark me-2">Edit</button>
            </form>
            <form action="{% url "todo:delete_task" task.pk %}" method="get" style="display: inline;">
            <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this task?')" >Delete</button>
            </form>
        </div>
    </li>
    {% endfor %}
</ul>

<nav aria-label="Page navigation example" class="mt-4">
    <ul class="pagination justify-content-center">
        {% if task_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ task_list.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for page_num in task_list.paginator.page_range %}
            {% if page_num == task_list.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if task_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ task_list.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>


{% endblock  %}